server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: springboot
    url: jdbc:h2:mem:testdb
    username: springboot
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true